
name: Backend_Deployment

on:
  push:
    branches: [ "feature/bojbackOpentelemetry" ]
    paths:
    - back/**
  pull_request:
    branches:  [ "develop" ]
    paths:
    - back/**

env:
    # Use docker.io for Docker Hub if empty
    # REGISTRY: ghcr.io
    # github.repository as <account>/<repo>
    IMAGE_NAME: "bojpawnapi"
jobs:
    build-backend:
        runs-on: ubuntu-latest   
        outputs:
            image_tag: ${{ steps.meta.outputs.tags }}
        #environment: dev
        defaults:
            run:
              working-directory: ./back/bojpawnapi
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v3
            - name: pwd 0
              run: pwd
            - uses: benjlevesque/short-sha@v2.2
              id: short-sha
              with:
                length: 6
            - run: echo $SHA
              env:
                SHA: ${{ steps.short-sha.outputs.sha }}
            - run: echo $SHA
              env:
                SHA: ${{ env.SHA }}
            # Set up BuildKit Docker container builder to be able to build
            # multi-platform images and export cache
            # https://github.com/docker/setup-buildx-action
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
                
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
               images: |
                ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
               tags: |
                 type=sha,prefix=dev-

            # Build and push Docker image with Buildx (don't push on PR)
            # https://github.com/docker/build-push-action
            - name: Build and push Docker image
              id: build-and-push
              uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
              with:
                context: .
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}